services:
  multitenantems.api:
    image: ${DOCKER_REGISTRY-}multitenantemsapi
    build:
      context: ..
      dockerfile: src/MultiTenantEMS.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      Jwt__Secret: ${Jwt__Secret}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      ASPNETCORE_ENVIRONMENT: ${Environment}
      Logging__LogLevel__Default: ${LogLevel}
      DATABASE_SERVER: ${DATABASE_SERVER}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DATABASENAME: ${DATABASE_DATABASENAME}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASENAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DATABASENAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
